FROM redis:8.4.0-bookworm

RUN mkdir -p /var/log/redis /data \
    && chown -R redis:redis /var/log/redis /data

COPY redis/redis.conf /usr/local/etc/redis/redis.conf

CMD ["sh", "-c", "set -e; \
    if [ -n \"${REDIS_PASSWORD}\" ]; then \
    exec redis-server /usr/local/etc/redis/redis.conf --requirepass \"${REDIS_PASSWORD}\"; \
    else \
    exec redis-server /usr/local/etc/redis/redis.conf; \
    fi"]
