FROM redis:7.4-alpine

RUN mkdir -p /var/log/redis /data \
    && chown -R redis:redis /var/log/redis /data

CMD ["sh","-c","if [ -n \"$REDIS_PASSWORD\" ]; then exec redis-server --requirepass \"$REDIS_PASSWORD\"; else exec redis-server; fi"]
